language: python
python:
  - "3.5"
before_install:
  - pip install pytest pytest-cov
  - pip install coveralls
  - pip install portalocker
# command to run tests
script: 
  - py.test --cov-report term-missing --cov timeseries/timeseries/ timeseries/timeseries/tests/
  - py.test --cov-report term-missing --cov cs207rbtree/cs207rbtree/ cs207rbtree/cs207rbtree/tests/

after_success:
  - coveralls

notifications:
  email: false